packageExtensions:
  "@codecov/rollup-plugin":
    peerDependenciesMeta:
      rollup:
        optional: true
  conventional-changelog-preset-loader:
    peerDependencies:
      conventional-changelog-conventionalcommits: ^10.0.0
    peerDependenciesMeta:
      "conventional-changelog-core":
        optional: true

virtualStoreType: global

minimumReleaseAgeExclude:
  - "@mr-hope/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@vitest/*"
  - "@vue/*"
  - "oxc-config-hope"
  - "oxfmt"
  - "oxlint"
  - "vitest"

trustPolicy: no-downgrade

minimumReleaseAgeExcludePrune: true
trustPolicyExcludePrune: true
trustPolicyIgnoreAfter: 720
