overrides:
  # FIXME: avoid outdated dependencies introducing vulnerable undici
  "@codecov/bundler-plugin-core@1>@actions/core": npm:@actions/core@2
  "@codecov/bundler-plugin-core@1>@actions/github": npm:@actions/github@8

packageExtensions:
  "@codecov/rollup-plugin":
    peerDependenciesMeta:
      rollup:
        optional: true
